---
- name: Add cronjob for docker volume snapshot
  cron:
    name: dockervolumesnap
    hour: "{{ lvssnap_creation_time.hour }}"
    minute: "{{ lvssnap_creation_time.minute }}"
    state: present
    job: "/usr/bin/umount {{ lvssnap_snapshot_mountpoint }} ; /usr/sbin/lvremove {{ lvssnap_snapshot_device }} -f ; (/usr/bin/docker ps -q --no-trunc | /usr/bin/xargs docker pause) ; (/usr/bin/mkdir -p {{ lvssnap_snapshot_mountpoint }} && /usr/sbin/lvcreate -l100\\%FREE -s -n docker_snap {{ lvssnap_lv_device }} && /usr/bin/mount {{ lvssnap_snapshot_device }} {{ lvssnap_snapshot_mountpoint }}) ; (/usr/bin/docker ps -q --no-trunc | /usr/bin/xargs docker unpause)"

- name: Add cronjob for removing docker volume snapshot
  cron:
    name: dockervolumesnap-remove
    hour: "{{ lvssnap_deletion_time.hour }}"
    minute: "{{ lvssnap_deletion_time.minute }}"
    state: present
    job: "/usr/bin/umount {{ lvssnap_snapshot_mountpoint }} ; /usr/sbin/lvremove {{ lvssnap_snapshot_device }} -f"
